version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      # Optional: for development - mount your Express app for live changes
      - ./exprems:/app/exprems
    restart: unless-stopped