version: '3.8'

services:
  express-app:
    build: ./exprems
    # Don't expose ports - only accessible from nginx
    networks:
      - app-network
    restart: unless-stopped
    # This allows Docker Compose to scale this service
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - express-app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge