version: '3.8'

services:
  express-app-1:
    build: ./exprems
    container_name: express-app-1
    # Don't expose ports - only accessible from nginx
    networks:
      - app-network
    restart: unless-stopped

  express-app-2:
    build: ./exprems
    container_name: express-app-2
    # Don't expose ports - only accessible from nginx
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - express-app-1
      - express-app-2
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge